export const projects = [
  {
    title: 'Share Me',
    description: "It is a Social Media Image sharing web application created with React JS and Sanity.io. Implemented Masonry Layout Design and Google Sign-In Authentication.",
      image: '/images/SharemeAppImg.png',
      tags: ['React', 'Sanity'],
    source: 'https://shareme-fz.netlify.app/',
    github: 'https://github.com/Faraaz2633/shareme',
  },
  {
    title: 'CRWN Clothing',
    description:"It is an E-commerce web application created with React JS and Firebase. Implemented Google Sign in Authentication and Implemented Stripe Api for payments.",
    image: '/images/CrwnClothing.png',
    tags: ['React', 'Redux', 'Firebase'],
    source: 'https://crwn-clothing-fz.herokuapp.com/',
    github: 'https://github.com/Faraaz2633/crwn-clothing',
  },
  {
    title: 'Unichat',
    description: "It Is An Web Application Created With React JS, Firebase And Chat Engine API. It Allows Users To Chat And Share Files With Each Others.",
    image: '/images/Unichat.jpg',
    tags: ['React', 'ChatEngine', 'Firebase'],
    source: 'https://unichat-md.netlify.app/',
    github: 'https://github.com/Faraaz2633/unichat',
  },
  {
    title: 'Frecipe',
    description: "It Is An Progressive Web Application Created With React JS. It Allows Users To View Reciepes Of Various Dishes.",
      image: '/images/Frecipe.png',
      tags: ['React'],
    source: 'https://frecipe.netlify.app/',
    github: 'https://frecipe.netlify.app/',
  },
  {
    title: 'Todo App',
    description: "Todo App created with React JS and Tailwind, It allows users to use CRUD operations. It stores data in local storage",
    image: '/images/todoApp.png',
    tags: ['React', 'Tailwind'],
    source: 'https://todo-app-fz.netlify.app/',
    github: 'https://github.com/Faraaz2633/todo-app',
  },
  {
    title: 'Weather App',
    description: "It Is A Simple Weather App Which Shows Weather Of The Entered City. It Uses Open Weather API to fetch data.",
    image: '/images/weatherApp.png',
    tags: ['JavaScript', 'HTML', 'CSS'],
    source: 'https://faraaz2633.github.io/weather-app/',
    github: 'https://github.com/Faraaz2633/weather-app',
  },
  {
    title: 'MineSweeper Game',
    description: "MineSweeper Game Created With HTML, CSS, & JavaScript. It has 3 levels, Easy, Medium and Hard",
    image: '/images/mineSweeper.png',
    tags: ['JavaScript', 'HTML', 'CSS'],
    source: 'https://minesweeper-md.netlify.app/',
    github: 'https://github.com/Faraaz2633/Mine-Sweeper',
  },
  {
    title: 'Blue Notes',
    description: "It Is An Notes Taking Website Created With HTML, CSS And JavaScript. It uses localstorage to store data",
    image: '/images/blueNotes.png',
    tags: ['JavaScript', 'HTML', 'CSS'],
    source: 'https://bluenotes.netlify.app/',
    github: 'https://github.com/Faraaz2633/Blue-Notes',
  },
  {
    title: 'Monsters Rolodex',
    description: "It Is Simple React Project, It Updates Through Fetch API",
    image: '/images/monstersRolodex.png',
    tags: ['React'],
    source: 'https://faraaz2633.github.io/monster-rolodex/',
    github: 'https://github.com/Faraaz2633/monster-rolodex',
  },
  {
    title: 'Type Ahead',
    description: "In This Website It Displays The Population Of The Entered City/State In USA. It Uses Fetch API",
    image: '/images/typeAhead.png',
    tags: ['JavaScript', 'HTML', 'CSS'],
    source: 'https://md-day06.netlify.app/',
    github: 'https://github.com/Faraaz2633/JavaScript30/tree/main/Day%2006%20Ajax%20-%20Type%20Ahead',
  },
  {
    title: 'CSS in JS',
    description: "It Updates The CSS Variables On Change Through JavaScript",
    image: '/images/cssInJS.png',
    tags: ['JavaScript', 'HTML', 'CSS'],
    source: 'https://md-day03.netlify.app/',
    github: 'https://github.com/Faraaz2633/JavaScript30/tree/main/Day%2003%20CSS%20Variables%20in%20JS',
  },
  {
    title: 'Payment Gateway',
    description: "In This Website I Have Done Simple Payment Gateway Integration Through Razor Pay.",
    image: '/images/paymentIntegration.png',
    tags: ['JavaScript', 'HTML', 'CSS'],
    source: 'https://tsf-faraz-task-1.netlify.app/',
    github: 'https://github.com/Faraaz2633/Payment-Gateway-Integration',
  },
  {
    title: 'Clock',
    description: "It Is A Simple CSS And JavaScript Clock",
    image: '/images/clock.png',
    tags: ['JavaScript', 'HTML', 'CSS'],
    source: 'https://md-day02.netlify.app/',
    github: 'https://github.com/Faraaz2633/JavaScript30/tree/main/Day%2002%20Clock',
  },
  {
    title: 'Drumkit',
    description: "It Has A Basic Drum Kit, It Plays Sound On Key Press",
    image: '/images/drumkit.png',
    tags: ['JavaScript', 'HTML', 'CSS'],
    source: 'https://md-day01.netlify.app/',
    github: 'https://github.com/Faraaz2633/JavaScript30/tree/main/Day%2001%20Drum%20Kit',
  },
];

export const TimeLineData = [
  { year: 2017, text: 'Started my journey', },
  { year: 2018, text: 'Worked as a freelance developer', },
  { year: 2019, text: 'Founded JavaScript Mastery', },
  { year: 2020, text: 'Shared my projects with the world', },
  { year: 2021, text: 'Started my own platform', },
];